### ISSUE TITLE
oca.decorators.foreach: Doesn't work or not properly used

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-decorators#8] opened 2017-11-01 19:00 UTC
As there's no instruction on how to use it, I have made this sample code:

```python
import oca.decorators
from odoo import models, fields


class Model(models.Model):
    _name = 'test'

    field = fields.Boolean(compute="_compute_field")

    @oca.decorators.foreach
    def _compute_field(self):
        self.field = False
```

and I get the error:
<details>
Odoo Server Error

Traceback (most recent call last):
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/models.py", line 5305, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/models.py", line 3208, in read
    result = BaseModel.read(records, fields, load=load)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/models.py", line 3254, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/models.py", line 5769, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/fields.py", line 831, in __get__
    self.determine_value(record)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/fields.py", line 940, in determine_value
    self.compute_value(recs)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/fields.py", line 895, in compute_value
    self._compute_value(records)
  File "/Datos/Installs/ERP/odoo/9.0/odoo-community/openerp/fields.py", line 885, in _compute_value
    getattr(records, self.compute)()
  File "/usr/local/lib/python2.7/dist-packages/oca/decorators/foreach.py", line 72, in _foreach
    wrapper = decorator(loop, method)
  File "/usr/lib/python2.7/dist-packages/decorator.py", line 239, in decorator
    return decorate(_func, caller)
  File "/usr/lib/python2.7/dist-packages/decorator.py", line 229, in decorate
    evaldict, __wrapped__=func)
  File "/usr/lib/python2.7/dist-packages/decorator.py", line 216, in create
    self = cls(func, name, signature, defaults, doc, module)
  File "/usr/lib/python2.7/dist-packages/decorator.py", line 99, in __init__
    self.name = func.__name__
AttributeError: 'test' object has no attribute '__name__'
</details>

Am I doing anything wrong?

**Comment by pedrobaeza** [comment] 2017-11-01 19:09
It seems `@oca.decorators.foreach()` works, but the syntax is different then than `@api.one`.

**Comment by yajo** [comment] 2017-11-03 12:51
The docs are inline, the addition of `()` is needed because the decorator purpose is slightly different from `@api.one`, since it tries to be more specific about what it does, thus not returning a `list` always, but allowing to be aggregated under any kind of iterable.

Current docs: 

https://github.com/OCA/oca-decorators/blob/fad59694b9ddf23e8da1449a116308c25ee2e2ab/oca/decorators/foreach.py#L9-L60

So, apart from that, this is a duplicate of #5. Closing as such.

**Closed as completed by yajo** 2017-11-03 12:51 UTC
